// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mumak.Indexer.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mumak.Indexer.Migrations
{
    [DbContext(typeof(MumakDbContext))]
    [Migration("20240910100707_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cardano.Sync.Data.Models.ReducerState", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Slot")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Name");

                    b.ToTable("ReducerStates", "public");
                });

            modelBuilder.Entity("Mumak.Indexer.Data.Utxo", b =>
                {
                    b.Property<decimal>("Slot")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("slot");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal>("TxIndex")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("tx_index");

                    b.Property<byte[]>("Raw")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("raw");

                    b.HasKey("Slot", "Id", "TxIndex");

                    b.ToTable("utxos", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
